import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import '../../utilis/custom_text.dart';

class Page1 extends StatefulWidget {
  const Page1({super.key});

  @override
  State<Page1> createState() => _Page1State();
}

class _Page1State extends State<Page1> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 5,
        centerTitle: true,
        automaticallyImplyLeading: false,
        backgroundColor: Colors.blue,
        title: CustomText(
          text: "Resume",
          fontFamily: "Mulish",
          color: Colors.white,
          fontSize: 24.sp,
          fontWeight: FontWeight.bold,
        ),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: 18.0.w),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            children: [
              CustomText(
                text: "IMPRESSIVE RESUMES EASY ONLINE BUILDER",
                fontWeight: FontWeight.bold,
                fontSize: 20.sp,
              ),
              SizedBox(
                height: 10.h,
              ),
              Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(
                    Icons.arrow_forward_outlined,
                    size: 16.sp,
                  ),
                  Expanded(
                    child: CustomText(
                        text:
                            "Professional out-of-the-box resumes, instantly generated by the most advanced resume builder technology available."),
                  )
                ],
              ),
              SizedBox(
                height: 5.h,
              ),
              Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(
                    Icons.arrow_forward_outlined,
                    size: 16.sp,
                  ),
                  Expanded(
                    child: CustomText(
                        text:
                            "Effortless crafting. Real-time preview & pre-written resume examples.Dozens of HR-approved resume templates."),
                  )
                ],
              ),
              SizedBox(
                height: 5.h,
              ),
              Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(
                    Icons.arrow_forward_outlined,
                    size: 16.sp,
                  ),
                  Expanded(
                    child: CustomText(
                        text:
                            "Land your dream job with the perfect resume employers are looking for!"),
                  )
                ],
              ),
              SizedBox(
                height: 20.h,
              ),
              ElevatedButton(
                style: ElevatedButton.styleFrom(
                    shape: ContinuousRectangleBorder(),
                    backgroundColor: Colors.blueAccent),
                onPressed: () {},
                child: CustomText(
                  text: 'Start My Resume',
                  color: Colors.white,
                ),
              ),
              SizedBox(
                height: 30.h,
              ),
              SizedBox(
                height: 15.h,
              ),
              CustomText(
                color: Colors.blue.shade400,
                text: "3 EASY STEPS TO CREATE YOUR PERFECT RESUME",
                textDecoration: TextDecoration.underline,
              ),
              Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Container(
                    height: 50.h,
                    width: 50.w,
                    decoration: BoxDecoration(
                        shape: BoxShape.circle, color: Colors.blue.shade500),
                    child: Icon(Icons.pending_actions),
                  ),
                  SizedBox(
                    height: 15.h,
                  ),
                  CustomText(text: "CHOOSE YOUR RESUME TEMPLATE"),
                  SizedBox(
                    height: 15.h,
                  ),
                  CustomText(
                      text:
                          "Our professional resume templates are designed strictly following all industry guidelines and best practices that employers look for.")
                ],
              ),
              SizedBox(
                height: 15.h,
              ),
              SizedBox(
                height: 30.h,
                child: VerticalDivider(),
              ),
              SizedBox(
                height: 15.h,
              ),
              Column(
                children: [
                  Container(
                    height: 50.h,
                    width: 50.w,
                    decoration: BoxDecoration(
                        shape: BoxShape.circle, color: Colors.blue.shade500),
                    child: Icon(Icons.pending_actions),
                  ),
                  SizedBox(
                    height: 15.h,
                  ),
                  CustomText(text: "SHOW WHAT YOU'RE MADE OF"),
                  SizedBox(
                    height: 15.h,
                  ),
                  CustomText(
                      text:
                          "Not finding the right words to showcase yourself? We´ve added thousands of pre-written examples and resume samples. As easy as clicking.")
                ],
              ),
              SizedBox(
                height: 15.h,
              ),
              SizedBox(
                height: 30.h,
                child: VerticalDivider(),
              ),
              SizedBox(
                height: 15.h,
              ),
              Column(
                children: [
                  Container(
                    height: 50.h,
                    width: 50.w,
                    decoration: BoxDecoration(
                        shape: BoxShape.circle, color: Colors.blue.shade500),
                    child: Icon(Icons.pending_actions),
                  ),
                  SizedBox(
                    height: 15.h,
                  ),
                  CustomText(text: "DOWNLOAD YOUR RESUME"),
                  SizedBox(
                    height: 15.h,
                  ),
                  CustomText(
                      text:
                          "Start impressing employers. Download your awesome resume and land the job you are looking for, effortlessly.")
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
